version: "3"

services:
  app:
    build: ./
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db

  db:
    build: ./docker/mysql
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fmqai
