<!--used for centering-->
<div id="mainBody">
<div id="footer">
<br /><br /><br />
<a href="http://www.cms.hhs.gov/ESRDGeneralInformation/" target="_blank" class="footermenu">ESRD</a>&nbsp;|
&nbsp;<a href="http://www.cms.hhs.gov/" target="_blank" class="footermenu">CMS</a>&nbsp;|
&nbsp;<a href="http://fmqai.com/" target="_blank" class="footermenu">FMQAI</a>&nbsp;|
&nbsp;<a href="index_508.php" target="_self" class="footermenu">Text Only (508)</a>&nbsp;|
&nbsp;<a href="https://davidjeddy.com" target="_blank" class="footermenu">David Eddy</a>
<br />
<a href="http://get.adobe.com/reader/" target="_blank" class="footermenu"><img src="gui/acrobatreader.jpg" height="32" width="32" border="0" alt="Acrobat Reader"  longdesc="Get Acrobat Reader." /></a>
</div>
</div>